---
version: "3"
services:
  database:
    image: postgres:12.1-alpine
    container_name: database
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: orm_base
    ports:
      - "5433:5432"
    volumes:
      - ~/docker_volumes/db_orm/data/postgres:/var/lib/postgresql/data/
